# Generated by Django 3.2.4 on 2021-07-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('EXAME', 'Exame laboratorial'), ('DIAGN', 'Condições crônicas'), ('FOLLO', 'Follow-up'), ('REFS', 'Referência ao nível secundário'), ('HOSPT', 'Internação hospitalar')], default='EXAME', max_length=5)),
                ('risco', models.FloatField()),
                ('oportunidades', models.PositiveIntegerField()),
                ('ocorrencias', models.PositiveIntegerField()),
                ('ponto', models.FloatField(default=1)),
                ('upper', models.FloatField(default=1)),
                ('lower', models.FloatField(default=1)),
            ],
        ),
    ]
