# Generated by Django 2.2.7 on 2021-06-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210620_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duvidas',
            name='Date',
        ),
    ]
