# Generated by Django 2.2.7 on 2021-06-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_duvidas_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duvidas',
            options={},
        ),
        migrations.RenameField(
            model_name='duvidas',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='duvidas',
            old_name='Duvida',
            new_name='duvida',
        ),
    ]
