# Generated by Django 2.2.7 on 2021-06-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210620_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duvidas',
            options={'verbose_name': 'Duvida', 'verbose_name_plural': 'Duvidas'},
        ),
    ]
