# Generated by Django 2.2.7 on 2021-06-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210620_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duvidas',
            old_name='descricao',
            new_name='Descricao',
        ),
        migrations.RenameField(
            model_name='duvidas',
            old_name='duvida',
            new_name='Duvida',
        ),
        migrations.AddField(
            model_name='duvidas',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
