# Generated by Django 2.2.7 on 2021-06-22 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20210622_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='duvidas',
            name='novidade',
            field=models.BooleanField(default=True, verbose_name='Esta dúvida é nova para você?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duvidas',
            name='dificuldade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Qual o grau de dificuldade desta dúvida?'),
        ),
    ]
